include: package:purple_metrics_lints/purple_metrics_lints.yaml

analyzer:
  plugins:
    - drift
  exclude:
    - 'tool/google_localizer/**'
    - 'lib/generated_plugin_registrant.dart'
    - '**/*.select.dart'
