analyzer:
  exclude: [build/**, "**/*.freezed.dart", "**/*.g.dart"]
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    avoid_dynamic_calls: error
    avoid_slow_async_io: error
    cancel_subscriptions: error
    close_sinks: error
    control_flow_in_finally: error
    iterable_contains_unrelated_type: error
    list_remove_unrelated_type: error
    no_adjacent_strings_in_list: error
    no_duplicate_case_values: error
    no_logic_in_create_state: error
    prefer_void_to_null: error
    throw_in_finally: error
    always_declare_return_types: error
    avoid_catches_without_on_clauses: error
    avoid_catching_errors: error
    avoid_field_initializers_in_const_classes: error
    avoid_implementing_value_types: error
    avoid_init_to_null: error
    avoid_returning_null_for_void: error
    avoid_setters_without_getters: error
    avoid_unused_constructor_parameters: error
    avoid_void_async: error
    await_only_futures: error
    cast_nullable_to_non_nullable: error
    curly_braces_in_flow_control_structures: error
    empty_catches: error
    empty_constructor_bodies: error
    exhaustive_cases: error
    file_names: error
    join_return_with_assignment: error
    leading_newlines_in_multiline_strings: error
    library_names: error
    missing_whitespace_between_adjacent_strings: error
    omit_local_variable_types: error
    only_throw_errors: error
    overridden_fields: error
    parameter_assignments: error
    prefer_asserts_with_message: error
    prefer_collection_literals: error
    prefer_conditional_assignment: error
    prefer_const_constructors: error
    prefer_const_constructors_in_immutables: error
    prefer_const_declarations: error
    prefer_const_literals_to_create_immutables: error
    prefer_contains: error
    prefer_expression_function_bodies: error
    prefer_final_fields: error
    prefer_final_in_for_each: error
    prefer_final_locals: error
    provide_deprecation_message: error
    recursive_getters: error
    sort_child_properties_last: error
    type_annotate_public_apis: error
    override_on_non_overriding_member: error
    unnecessary_statements: error
    type_init_formals: error
    unawaited_futures: error
    unnecessary_await_in_return: error
    unnecessary_brace_in_string_interps: error
    unnecessary_const: error
    unnecessary_getters_setters: error
    unnecessary_lambdas: error
    unnecessary_new: error
    unnecessary_null_aware_assignments: error
    unnecessary_null_in_if_null_operators: error
    unnecessary_overrides: error
    unnecessary_parenthesis: error
    use_full_hex_values_for_flutter_colors: error
    use_function_type_syntax_for_parameters: error
    use_is_even_rather_than_modulo: error

linter:
  rules:
    # --- Error Rules ---
    - always_use_package_imports
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_returning_null_for_future
    - avoid_slow_async_io 
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - invariant_booleans # experimental
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_logic_in_create_state
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - unsafe_html
    - use_build_context_synchronously # experimental
    - valid_regexps

    # --- Style Rules ---
    - always_declare_return_types
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_implementing_value_types
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_multiple_declarations_per_line 
    - avoid_null_checks_in_equality_operators
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - curly_braces_in_flow_control_structures
    - deprecated_consistency
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - exhaustive_cases
    - file_names
    - implementation_imports
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - lines_longer_than_80_chars
    - missing_whitespace_between_adjacent_strings
    - no_default_cases # experimental
    - no_runtimeType_toString
    - non_constant_identifier_names
    # - noop_primitive_operations
    - null_check_on_nullable_type_parameter # experimental
    - null_closures
    - omit_local_variable_types
    - only_throw_errors
    - overridden_fields
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_with_message
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_expression_function_bodies 
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    # - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - recursive_getters
    # - require_trailing_commas # experimental 
    - sized_box_for_whitespace
    - slash_for_doc_comments
    - sort_child_properties_last
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    # - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks # experimental
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations # experimental 
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables # experimental
    - use_named_constants
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - void_checks