targets:
  $default:
    sources:
      - $package$
      - asset/**
      - lib/**
      - test/**
      - pubspec.yaml
    builders:
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/**
            - test/**
      freezed:
        enabled: true
        generate_for:
          include:
            - lib/**
            - test/**
      drift_dev:
        enabled: true
        options:
          data_class_to_companions: false
