publish_to: none
name: makefile_documentation_generator
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  md:
    git:
      url: git@github.com:purplenoodlesoop/parsing-and-rendering.git
      path: packages/md
  makefile:
    git:
      url: git@github.com:purplenoodlesoop/parsing-and-rendering.git
      path: packages/makefile
  stream_transform: ^2.0.1

#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
